---
# Binary installation
# Used when the system has no packages available
- name: "Determine if the correct server binary is already installed"
  stat:
    path: "/usr/local/bin/prometheus"
  register: "__stat_prometheus"

- debug:
    var: __stat_promethues
