---
- name: "Install the node exporter exporter"
  package:
    name: "prometheus-node-exporter"
    state: "present"

- name: "Configure the boot arguments"
  template:
    src: "etc/default/defaults.j2"
    dest: "/etc/default/prometheus-node-exporter"
  vars:
    __sitewards__prometheus__args: "{{ sitewards__prometheus__node_exporter_args }}"
  notify: "restart prometheus-node-exporter"
