---
- name: "restart prometheus-server"
  service:
    name: "prometheus"
    state: "restarted"

- name: "restart prometheus-node-exporter"
  service:
    name: "prometheus-node-exporter"
    state: "restarted"
